### ISSUE TITLE
report a bug,ModuleNotFoundError: No module named 'assets_lookup'`

### ISSUE THREAD

**Issue by liangqx-hku** [wangyian-me/thinshelllab#1]
Dear author,

Thanks for your sharing your awesome work!
When I tried to run this code, however I encounted a bug as follow:
`Traceback (most recent call last):
  File "/home/xxx/ThinShellLab/code/training/trajopt_folding.py", line 34, in <module>
    from thinshelllab.engine.render_engine import Renderer
  File "/home/xxx/ThinShellLab/code/engine/render_engine.py", line 6, in <module>
    from assets_lookup import texture_lookup, model_lookup, background_lookup
ModuleNotFoundError: No module named 'assets_lookup'`
So, could you give me some suggestion to solve this issue?
Looking forward to your reply!

Best!

**Comment by wangyian-me** [comment]
Hi! So how did you solve that? Did you forget to `export PYTHONPATH=$PYTHONPATH:${PWD}/data/AssetLoader`?

**Comment by liangqx-hku** [comment]
It's my fault. The main issue is `assets_lookup` in` AssetLoader`, so I tried to add the path for `assets_lookup` right now, then it works well. Thx!
